// This file is part of Compact.
// Copyright (C) 2026 Midnight Foundation
// SPDX-License-Identifier: Apache-2.0
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  	http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated by compactc. Do not edit by hand.

#![allow(
    clippy::all,
    dead_code,
    unused_imports,
    unused_variables,
    unused_parens,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals
)]

use compact_runtime::*;
use std::marker::PhantomData;

compact_runtime::check_runtime_version!("0.16.100");

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum VerificationMethodType {
    Undefined = 0,
    JsonWebKey = 1,
}
impl Aligned for VerificationMethodType {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for VerificationMethodType {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for VerificationMethodType {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::Undefined),
            1 => Some(Self::JsonWebKey),
            _ => None,
        }
    }
}
impl From<VerificationMethodType> for compact_runtime::Value {
    fn from(v: VerificationMethodType) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}
impl compact_runtime::BinaryHashRepr for VerificationMethodType {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum VerificationMethodRelation {
    Undefined = 0,
    Authentication = 1,
    AssertionMethod = 2,
    KeyAgreement = 3,
    CapabilityInvocation = 4,
    CapabilityDelegation = 5,
}
impl Aligned for VerificationMethodRelation {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for VerificationMethodRelation {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for VerificationMethodRelation {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::Undefined),
            1 => Some(Self::Authentication),
            2 => Some(Self::AssertionMethod),
            3 => Some(Self::KeyAgreement),
            4 => Some(Self::CapabilityInvocation),
            5 => Some(Self::CapabilityDelegation),
            _ => None,
        }
    }
}
impl From<VerificationMethodRelation> for compact_runtime::Value {
    fn from(v: VerificationMethodRelation) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}
impl compact_runtime::BinaryHashRepr for VerificationMethodRelation {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum MapMutation {
    Undefined = 0,
    Insert = 1,
    Update = 2,
}
impl Aligned for MapMutation {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for MapMutation {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for MapMutation {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::Undefined),
            1 => Some(Self::Insert),
            2 => Some(Self::Update),
            _ => None,
        }
    }
}
impl From<MapMutation> for compact_runtime::Value {
    fn from(v: MapMutation) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}
impl compact_runtime::BinaryHashRepr for MapMutation {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum SetMutation {
    Undefined = 0,
    Insert = 1,
    Remove = 2,
}
impl Aligned for SetMutation {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for SetMutation {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for SetMutation {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::Undefined),
            1 => Some(Self::Insert),
            2 => Some(Self::Remove),
            _ => None,
        }
    }
}
impl From<SetMutation> for compact_runtime::Value {
    fn from(v: SetMutation) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}
impl compact_runtime::BinaryHashRepr for SetMutation {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum KeyType {
    EC = 0,
    RSA = 1,
    oct = 2,
    OKP = 3,
}
impl Aligned for KeyType {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for KeyType {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for KeyType {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::EC),
            1 => Some(Self::RSA),
            2 => Some(Self::oct),
            3 => Some(Self::OKP),
            _ => None,
        }
    }
}
impl From<KeyType> for compact_runtime::Value {
    fn from(v: KeyType) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}
impl compact_runtime::BinaryHashRepr for KeyType {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum CurveType {
    Ed25519 = 0,
    X25519 = 1,
    Jubjub = 2,
    P256 = 3,
    Secp256k1 = 4,
}
impl Aligned for CurveType {
    fn alignment() -> Alignment {
        u8::alignment()
    }
}
impl FieldRepr for CurveType {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        (*self as u8).field_repr(writer);
    }
    fn field_size(&self) -> usize {
        1
    }
}
impl FromFieldRepr for CurveType {
    const FIELD_SIZE: usize = 1;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        let n = u8::from_field_repr(r)?;
        match n {
            0 => Some(Self::Ed25519),
            1 => Some(Self::X25519),
            2 => Some(Self::Jubjub),
            3 => Some(Self::P256),
            4 => Some(Self::Secp256k1),
            _ => None,
        }
    }
}
impl From<CurveType> for compact_runtime::Value {
    fn from(v: CurveType) -> compact_runtime::Value {
        compact_runtime::Value::from(v as u8)
    }
}
impl compact_runtime::BinaryHashRepr for CurveType {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        (*self as u8).binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        1
    }
}
#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct PublicKeyJwk {
    pub kty: KeyType,
    pub crv: CurveType,
    pub x: compact_runtime::std_lib::OpaqueString,
    pub y: compact_runtime::std_lib::OpaqueString,
}
impl Aligned for PublicKeyJwk {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<KeyType as Aligned>::alignment(),
            &<CurveType as Aligned>::alignment(),
            &<compact_runtime::std_lib::OpaqueString as Aligned>::alignment(),
            &<compact_runtime::std_lib::OpaqueString as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for PublicKeyJwk {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.kty.field_repr(writer);
        self.crv.field_repr(writer);
        self.x.field_repr(writer);
        self.y.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.kty.field_size() + self.crv.field_size() + self.x.field_size() + self.y.field_size()
    }
}
impl FromFieldRepr for PublicKeyJwk {
    const FIELD_SIZE: usize = <KeyType as FromFieldRepr>::FIELD_SIZE
        + <CurveType as FromFieldRepr>::FIELD_SIZE
        + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE
        + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let kty = <KeyType as FromFieldRepr>::from_field_repr(
            &r[_offset.._offset + <KeyType as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <KeyType as FromFieldRepr>::FIELD_SIZE;
        let crv = <CurveType as FromFieldRepr>::from_field_repr(
            &r[_offset.._offset + <CurveType as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <CurveType as FromFieldRepr>::FIELD_SIZE;
        let x = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::from_field_repr(
            &r[_offset
                .._offset + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
        let y = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::from_field_repr(
            &r[_offset
                .._offset + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(PublicKeyJwk { kty, crv, x, y })
    }
}
impl From<PublicKeyJwk> for compact_runtime::Value {
    fn from(s: PublicKeyJwk) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.kty));
        _v.push(compact_runtime::Value::from(s.crv));
        _v.push(compact_runtime::Value::from(s.x));
        _v.push(compact_runtime::Value::from(s.y));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for PublicKeyJwk {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.kty.binary_repr(writer);
        self.crv.binary_repr(writer);
        self.x.binary_repr(writer);
        self.y.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.kty.binary_len() + self.crv.binary_len() + self.x.binary_len() + self.y.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct VerificationMethod {
    pub id: compact_runtime::std_lib::OpaqueString,
    pub typ: VerificationMethodType,
    pub publicKeyJwk: PublicKeyJwk,
}
impl Aligned for VerificationMethod {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<compact_runtime::std_lib::OpaqueString as Aligned>::alignment(),
            &<VerificationMethodType as Aligned>::alignment(),
            &<PublicKeyJwk as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for VerificationMethod {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.id.field_repr(writer);
        self.typ.field_repr(writer);
        self.publicKeyJwk.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.id.field_size() + self.typ.field_size() + self.publicKeyJwk.field_size()
    }
}
impl FromFieldRepr for VerificationMethod {
    const FIELD_SIZE: usize = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE
        + <VerificationMethodType as FromFieldRepr>::FIELD_SIZE
        + <PublicKeyJwk as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let id = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::from_field_repr(
            &r[_offset
                .._offset + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
        let typ = <VerificationMethodType as FromFieldRepr>::from_field_repr(
            &r[_offset.._offset + <VerificationMethodType as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <VerificationMethodType as FromFieldRepr>::FIELD_SIZE;
        let publicKeyJwk = <PublicKeyJwk as FromFieldRepr>::from_field_repr(
            &r[_offset.._offset + <PublicKeyJwk as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <PublicKeyJwk as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(VerificationMethod {
            id,
            typ,
            publicKeyJwk,
        })
    }
}
impl From<VerificationMethod> for compact_runtime::Value {
    fn from(s: VerificationMethod) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.id));
        _v.push(compact_runtime::Value::from(s.typ));
        _v.push(compact_runtime::Value::from(s.publicKeyJwk));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for VerificationMethod {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.id.binary_repr(writer);
        self.typ.binary_repr(writer);
        self.publicKeyJwk.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.id.binary_len() + self.typ.binary_len() + self.publicKeyJwk.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SchnorrJubjubVerificationMethod {
    pub id: compact_runtime::std_lib::OpaqueString,
    pub publicKey: JubjubPoint,
}
impl Aligned for SchnorrJubjubVerificationMethod {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<compact_runtime::std_lib::OpaqueString as Aligned>::alignment(),
            &<JubjubPoint as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for SchnorrJubjubVerificationMethod {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.id.field_repr(writer);
        self.publicKey.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.id.field_size() + self.publicKey.field_size()
    }
}
impl FromFieldRepr for SchnorrJubjubVerificationMethod {
    const FIELD_SIZE: usize = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE
        + <JubjubPoint as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let id = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::from_field_repr(
            &r[_offset
                .._offset + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
        let publicKey = <JubjubPoint as FromFieldRepr>::from_field_repr(
            &r[_offset.._offset + <JubjubPoint as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <JubjubPoint as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(SchnorrJubjubVerificationMethod { id, publicKey })
    }
}
impl From<SchnorrJubjubVerificationMethod> for compact_runtime::Value {
    fn from(s: SchnorrJubjubVerificationMethod) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.id));
        _v.push(compact_runtime::Value::from(s.publicKey));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for SchnorrJubjubVerificationMethod {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.id.binary_repr(writer);
        self.publicKey.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.id.binary_len() + self.publicKey.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct Service {
    pub id: compact_runtime::std_lib::OpaqueString,
    pub typ: compact_runtime::std_lib::OpaqueString,
    pub serviceEndpoint: compact_runtime::std_lib::OpaqueString,
}
impl Aligned for Service {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<compact_runtime::std_lib::OpaqueString as Aligned>::alignment(),
            &<compact_runtime::std_lib::OpaqueString as Aligned>::alignment(),
            &<compact_runtime::std_lib::OpaqueString as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for Service {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.id.field_repr(writer);
        self.typ.field_repr(writer);
        self.serviceEndpoint.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.id.field_size() + self.typ.field_size() + self.serviceEndpoint.field_size()
    }
}
impl FromFieldRepr for Service {
    const FIELD_SIZE: usize = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE
        + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE
        + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let id = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::from_field_repr(
            &r[_offset
                .._offset + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
        let typ = <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::from_field_repr(
            &r[_offset
                .._offset + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
        let serviceEndpoint =
            <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::from_field_repr(
                &r[_offset
                    .._offset
                        + <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE],
            )?;
        _offset += <compact_runtime::std_lib::OpaqueString as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(Service {
            id,
            typ,
            serviceEndpoint,
        })
    }
}
impl From<Service> for compact_runtime::Value {
    fn from(s: Service) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.id));
        _v.push(compact_runtime::Value::from(s.typ));
        _v.push(compact_runtime::Value::from(s.serviceEndpoint));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for Service {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.id.binary_repr(writer);
        self.typ.binary_repr(writer);
        self.serviceEndpoint.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.id.binary_len() + self.typ.binary_len() + self.serviceEndpoint.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct SchnorrSignature {
    pub announcement: JubjubPoint,
    pub response: Fr,
}
impl Aligned for SchnorrSignature {
    fn alignment() -> Alignment {
        Alignment::concat([
            &<JubjubPoint as Aligned>::alignment(),
            &<Fr as Aligned>::alignment(),
        ])
    }
}
impl FieldRepr for SchnorrSignature {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.announcement.field_repr(writer);
        self.response.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.announcement.field_size() + self.response.field_size()
    }
}
impl FromFieldRepr for SchnorrSignature {
    const FIELD_SIZE: usize =
        <JubjubPoint as FromFieldRepr>::FIELD_SIZE + <Fr as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let announcement = <JubjubPoint as FromFieldRepr>::from_field_repr(
            &r[_offset.._offset + <JubjubPoint as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <JubjubPoint as FromFieldRepr>::FIELD_SIZE;
        let response = <Fr as FromFieldRepr>::from_field_repr(
            &r[_offset.._offset + <Fr as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <Fr as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(SchnorrSignature {
            announcement,
            response,
        })
    }
}
impl From<SchnorrSignature> for compact_runtime::Value {
    fn from(s: SchnorrSignature) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.announcement));
        _v.push(compact_runtime::Value::from(s.response));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for SchnorrSignature {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.announcement.binary_repr(writer);
        self.response.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.announcement.binary_len() + self.response.binary_len()
    }
}

#[derive(Clone, Debug, PartialEq, Eq, Default)]
pub struct ContractAddress {
    pub bytes: [u8; 32],
}
impl Aligned for ContractAddress {
    fn alignment() -> Alignment {
        Alignment::concat([&<[u8; 32] as Aligned>::alignment()])
    }
}
impl FieldRepr for ContractAddress {
    fn field_repr<W: MemWrite<Fr>>(&self, writer: &mut W) {
        self.bytes.field_repr(writer);
    }
    fn field_size(&self) -> usize {
        self.bytes.field_size()
    }
}
impl FromFieldRepr for ContractAddress {
    const FIELD_SIZE: usize = <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
    fn from_field_repr(r: &[Fr]) -> Option<Self> {
        if r.len() < Self::FIELD_SIZE {
            return None;
        }
        let mut _offset = 0usize;
        let bytes = <[u8; 32] as FromFieldRepr>::from_field_repr(
            &r[_offset.._offset + <[u8; 32] as FromFieldRepr>::FIELD_SIZE],
        )?;
        _offset += <[u8; 32] as FromFieldRepr>::FIELD_SIZE;
        let _ = _offset;
        Some(ContractAddress { bytes })
    }
}
impl From<ContractAddress> for compact_runtime::Value {
    fn from(s: ContractAddress) -> compact_runtime::Value {
        let mut _v: Vec<compact_runtime::Value> = Vec::new();
        _v.push(compact_runtime::Value::from(s.bytes));
        compact_runtime::Value::concat(_v.iter())
    }
}
impl compact_runtime::BinaryHashRepr for ContractAddress {
    fn binary_repr<W: MemWrite<u8>>(&self, writer: &mut W) {
        self.bytes.binary_repr(writer);
    }
    fn binary_len(&self) -> usize {
        self.bytes.binary_len()
    }
}

pub trait Witnesses<PS> {
    fn local_secret_key<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, [u8; 32]);
    fn current_timestamp<'a>(&self, ctx: &WitnessContext<Ledger<'a>, PS>) -> (PS, u64);
}

pub struct Contract<PS, W = NoWitnesses>
where
    W: Witnesses<PS>,
{
    pub witnesses: W,
    _ps: PhantomData<PS>,
}

impl<PS, W> Contract<PS, W>
where
    W: Witnesses<PS>,
{
    pub fn new(witnesses: W) -> Self {
        Self {
            witnesses,
            _ps: PhantomData,
        }
    }
    pub fn initial_state(
        &self,
        ctx: ConstructorContext<PS>,
    ) -> Result<ConstructorResult<PS>, CompactError> {
        let sv = new_array(vec![
            new_cell(0u32),
            new_cell([0u8; 32]),
            new_cell(ContractAddress::default()),
            new_map(),
            new_cell(0u64),
            new_cell(0u64),
            new_cell(0u64),
            new_cell(false),
            new_cell(false),
            new_cell(0u64),
            new_map(),
            new_map(),
            new_map(),
            new_map(),
            new_map(),
            new_map(),
            new_map(),
            new_map(),
        ]);
        let state = ChargedState::new(sv);
        let qctx = QueryContext::new(state, ContractAddress::default());
        Ok(ConstructorResult {
            current_contract_state: qctx.state,
            current_private_state: ctx.initial_private_state,
            current_zswap_local_state: ctx.empty_zswap_local_state,
        })
    }

    pub fn rotate_controller_key(
        &self,
        ctx: CircuitContext<PS>,
        new_controller_public_key: [u8; 32],
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn set_also_known_as(
        &self,
        ctx: CircuitContext<PS>,
        value: compact_runtime::std_lib::OpaqueString,
        mutation: SetMutation,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn set_verification_method(
        &self,
        ctx: CircuitContext<PS>,
        verification_method: VerificationMethod,
        mutation: MapMutation,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn remove_verification_method(
        &self,
        ctx: CircuitContext<PS>,
        id: compact_runtime::std_lib::OpaqueString,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn set_schnorr_jubjub_verification_method(
        &self,
        ctx: CircuitContext<PS>,
        verification_method: SchnorrJubjubVerificationMethod,
        mutation: MapMutation,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn remove_schnorr_jubjub_verification_method(
        &self,
        ctx: CircuitContext<PS>,
        id: compact_runtime::std_lib::OpaqueString,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn verify_schnorr_jubjub_digest_signature(
        &self,
        ctx: CircuitContext<PS>,
        method_id: compact_runtime::std_lib::OpaqueString,
        digest: [Fr; 4],
        signature: SchnorrSignature,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn set_verification_method_relation(
        &self,
        ctx: CircuitContext<PS>,
        relation: VerificationMethodRelation,
        method_id: compact_runtime::std_lib::OpaqueString,
        mutation: SetMutation,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn set_service(
        &self,
        ctx: CircuitContext<PS>,
        service: Service,
        mutation: MapMutation,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn remove_service(
        &self,
        ctx: CircuitContext<PS>,
        id: compact_runtime::std_lib::OpaqueString,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }

    pub fn deactivate(
        &self,
        ctx: CircuitContext<PS>,
    ) -> Result<CircuitResults<PS, ()>, CompactError> {
        let ops = OpProgramVerify::<DefaultDB>::new()
            .idx_at_index(0u8, true)
            .push(false, new_cell(0u8))
            .push(true, new_cell(1u8))
            .ins(false, 1)
            .ins(true, 1)
            .build();

        let results = query_for_verify(
            &ctx.current_query_context,
            &ops,
            ctx.gas_limit.clone(),
            &ctx.cost_model,
        )?;

        Ok(CircuitResults {
            result: (),
            context: CircuitContext {
                current_query_context: results.context,
                ..ctx
            },
            gas_cost: results.gas_cost,
        })
    }
}

pub struct Ledger<'a, D: DB = DefaultDB> {
    state: &'a ChargedState<D>,
}

pub fn ledger<D: DB>(state: &ChargedState<D>) -> Ledger<'_, D> {
    Ledger { state }
}

impl<'a, D: DB> Ledger<'a, D> {
    pub fn contract_version(&self) -> Result<u32, CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(0u8, false)
            .idx_at_index(0u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_u32(av)
    }
    pub fn controller_public_key(&self) -> Result<[u8; 32], CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(0u8, false)
            .idx_at_index(1u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_bytes::<32>(av)
    }
    pub fn id(&self) -> Result<ContractAddress, CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(0u8, false)
            .idx_at_index(2u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        /* TODO M3-R4: decoder for ContractAddress */
        compact_runtime::std_lib::decode_u64(av)
    }
    pub fn version(&self) -> Result<u64, CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .idx_at_index(1u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_u64(av)
    }
    pub fn created(&self) -> Result<u64, CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .idx_at_index(2u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_u64(av)
    }
    pub fn updated(&self) -> Result<u64, CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .idx_at_index(3u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_u64(av)
    }
    pub fn deactivated(&self) -> Result<bool, CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .idx_at_index(4u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_bool(av)
    }
    pub fn active(&self) -> Result<bool, CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .idx_at_index(5u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_bool(av)
    }
    pub fn operation_count(&self) -> Result<u64, CompactError> {
        let qctx = QueryContext::new(self.state.clone(), ContractAddress::default());
        let ops = OpProgramGather::<D>::new()
            .dup(0)
            .idx_at_index(1u8, false)
            .idx_at_index(6u8, false)
            .popeq(true)
            .build();
        let results = query_for_read(&qctx, &ops, None, &initial_cost_model())
            .map_err(|e| CompactError::AssertionFailed(format!("ledger query failed: {:?}", e)))?;
        let av = match results.events.last() {
            Some(compact_runtime::onchain_vm::result_mode::GatherEvent::Read(av)) => av,
            _ => {
                return Err(CompactError::AssertionFailed(
                    "ledger: expected Read event".into(),
                ))
            }
        };
        compact_runtime::std_lib::decode_u64(av)
    }
}

pub mod pure_circuits {
    use super::*;

    pub(crate) fn controller_key(sk: [u8; 32]) -> [u8; 32] {
        compact_runtime::std_lib::persistent_hash_aligned(&[
            compact_runtime::AlignedValue::from([
                100u8, 105, 100, 58, 99, 111, 110, 116, 114, 111, 108, 108, 101, 114, 58, 112, 107,
                0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            ]),
            compact_runtime::AlignedValue::from(sk),
        ])
    }
}
